### ISSUE TITLE
Do not clear another build on `ssc build`

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#54]
1) `ssc build` creates a `<builddir>/<os>/<name>-dev.app`
2) `ssc build --prod` removes `<builddir>/<os>/<name>-dev.app` and creates a `<builddir>/<os>/<name>.app` (without `-dev` suffix)
3) `ssc build` removes `<builddir>/<os>/<name>.app` and creates a `<builddir>/<os>/<name>-dev.app`

That's a bug. We should have both.

**Comment by aleclarson** [comment]
I don't think dev and prod would be able to share the same `{output}/{platform}/` folder? Can't guarantee the user's `build` script won't step on itself (erasing dev-specific artifacts when prod build runs).

I'd suggest going with `{output}/{platform}/{prod,dev}/` instead of sharing the same folder. Sorry if that's what you had planned already :)

**Comment by heapwolf** [comment]
fixed
