### ISSUE TITLE
How to download and install desktop app updates?

### ISSUE THREAD

**Issue by ccorcos** [socketsupply/socket#7]
Any advice on how to download and install app updates on desktop?

**Comment by heapwolf** [comment]
Apple and Google will allow you to do self-updates that don't violate the user's expectations, so small updates to javascript and html, etc. are fine, you can pull those down yourself with a server or p2p and just write them into `window.process.cwd()`. 

For updates of socket itself, it depends on what your goals are. But the easiest way is using the official channels (google play, apple store, etc), because it happens securely, everything is signed and notarized, the user gets batched updates with all their other software, etc etc.

Another way is to ping your own api (or receive a p2p message) and get the update, install it into place, tell the user there is an update and when they start the app again it will be updated.

**Comment by ccorcos** [comment]
> But the easiest way is using the official channels (google play, apple store, etc), because it happens securely, everything is signed and notarized, the user gets batched updates with all their other software, etc etc.

Yeah, so many apps don't do this though which makes me skeptical. I've heard so many problems about the Mac App Store. Sketch, Figma, Notion... so many apps aren't using the Mac App Store.

Sounds like a simple solution though. I didn't realize I can swap out the binary while the app is running, but it makes sense that would be loaded into memory. I'll try that out.
