### ISSUE TITLE
How to securely display a webview of external URL?

### ISSUE THREAD

**Issue by ccorcos** [socketsupply/socket#8]
I see in your documentation about security "NEVER try to build a browser. NEVER evaluate arbitrary code.". 

But is there a way to securely display a webview that loads an external website? My use case is currently just for displaying a checkout process for purchasing the app. But I can also imagine wanting to display website previews, etc.

Thanks!

**Comment by heapwolf** [comment]
If you want to load your own domain and only that domain, (`https://example.com` for example), you could hard code it into the html of your CSP. In theory, you can trust yourself, but I will make Apple and Google mad. They don't like apps that just load a website and they've been known to reject apps that do this. An exception to this rule might be, if you're using it like Apple Music, where only partial dynamic stuff (like albums songs artists etc is being loaded). 

But it sounds like you want to load an arbitrary url. And I wont enumerate the **many** things that can go wrong with this, but im not exaggerating how long this list of complicated problems is. Executing arbitrary code is why browsers are a nightmare of exploits. And that's why we have this warning. My best advice to you is to launch the user out to the website that needs to do the checkout page using the `openExtermal` method. Then have a link on that page that launches them back into the app.

My personal dislike about this sort of thing in general is that it's online-only, and we are heavily advocating offline, local-first user experiences.

**Comment by ccorcos** [comment]
> Executing arbitrary code is why browsers are a nightmare of exploits.

Hmm. Yeah, I don't necessarily want to build a full-blown browser, but there are a lot of nice features that could be enabled by this capability. 

For example, maybe you're writing a document and you embed a link. It would be nice to be able to hover over the link and see a little popup preview of the website in a webview.

Or maybe you want to build a bookmarking tool that will load a page and run [freeze-dry](https://www.npmjs.com/package/freeze-dry) to save it for archiving / offline reading / searching.

> My personal dislike about this sort of thing in general is that it's online-only, and we are heavily advocating offline, local-first user experiences.

I am 100% on board with offline  / local-first experiences 💯
